logiq-flash:
  replicaCount: 3
  image:
    tag: 1.2.0
  environment:
    flags_extra: "-event_workers 25 -workers 100 -timeout_inital_logs 1h"
  persistence:
    enabled: true
    storageClass: standard
    size: 10Gi

flash-discovery:
  fullnameOverride: flash-discovery
  image:
    tag: 1.2.0
  persistence:
    enabled: true
    storageClass: standard
    size: 2Gi

redis:
  fullnameOverride: redis
  usePassword: false
  cluster:
    slaveCount: 2

postgres:
  fullnameOverride: postgres
  postgresqlPostgresPassword: postgres
  postgresqlUsername: postgres
  postgresqlDatabase: postgres
  postgresqlPassword: postgres
  persistence:
    storageClass: standard
    size: 8Gi
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"

flash-brew-helm:
  pithos:
    image:
      tag: brew.1.2.0
    environment:
      heapspace: 10240
  beetle_coordinator:
    image: 
      tag: brew.1.2.0
    resources:
      requests:
        memory: "4Gi"
        cpu: "500m"
  beetle_worker:
    replicaCount: 2
    image: 
      tag: brew.1.2.0
    resources:
      requests:
        memory: "4Gi"
        cpu: "1000m"

flash-coffee:
  coffee:
    image: 
      tag: brew.1.2.0
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
  coffee_worker:
    replicaCount: 3
    image: 
      tag: brew.1.2.0
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"

s3-gateway:
  s3gateway:
    enabled: false
  fullnameOverride: s3-gateway
  accessKey: logiq_access
  secretKey: logiq_secret
  defaultBucket:
    enabled: true
    name: logiq
  persistence:
    enabled: true
    storageClass: standard
    size: 10Gi

ingress:
  enabled: true
  name: logiq-ingress
  tlsEnabled: true
  tlsSecretName: null

kubernetes-ingress:
  controller:
    replicaCount: 1
    ingressClass: logiq-ingress
    defaultTLSSecret:
      enabled: true
      secret: null

global:
  domain: null
  environment:
    redis_opts: true
    redis_host: "redis-master"
    redis_port: "6379"
    postgres_host: "postgres"
    postgres_port: "5432"
    postgres_user: "postgres"
    postgres_password: "postgres"
    postgres_db: "postgres"
    s3_url: "http://s3-gateway:9000"
    s3_access: "logiq_access"
    s3_secret: "logiq_secret"
    s3_bucket: "logiq"
    s3_region: "us-east-1"
