{{ if not .Values.configMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logiq-config
data:
  config.yaml: |
    
        options:
    
            ca: "/flash/certs/ca.crt"
    
            cert: "/flash/certs/syslog.crt"
    
            key: "/flash/certs/syslog.key"
    
            host: 0.0.0.0
    
        partitions:
    
          -
    
            name: p_scheme
    
            fields:
    
              - namespace
    
              - appname
    
              - year
    
              - month
    
              - day
    
        credentials:
    
          -
    
            name: logiq
    
            s3:
    
              secret_key: {{ .Values.global.environment.s3_secret }}
    
              access_key: {{ .Values.global.environment.s3_access}}
    
        destinations:
    
          -
    
            name: default_log_store
    
            partition: p_scheme
    
            s3:
    
              bucket: {{.Values.global.environment.s3_bucket}}
    
              endpoint: http://s3-gateway:9000
    
              region: {{.Values.global.environment.s3_region}}
    
              credential: logiq
    
        rules:
    
          -
    
            destination: default_log_store
{{ end }}
