apiVersion: v1
kind: Service
metadata:
  name: {{ template "logiq-flash.name" . }}
  labels:
    app: logiq-flash
    chart: {{ template "logiq-flash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.grpc.port }}
      targetPort: 50054
      protocol: TCP
      name: {{ .Values.grpc.name }}
    - port: {{ .Values.webcli.port }}
      targetPort: {{ .Values.webcli.port }}
      protocol: TCP
      name: {{ .Values.webcli.name }}
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: {{ .Values.api.name }}
    - port: {{ .Values.syslog.port }}
      targetPort: {{ .Values.syslog.containerPort }}
      protocol: TCP
      name: {{ .Values.syslog.name }}
    - port: {{ .Values.syslogtls.port }}
      targetPort: {{ .Values.syslogtls.port }}
      protocol: TCP
      name: {{ .Values.syslogtls.name }}
    - port: {{ .Values.relptls.port }}
      targetPort: {{ .Values.relptls.port }}
      protocol: TCP
      name: {{ .Values.relptls.name }}
    - port: {{ .Values.relp.port }}
      targetPort: {{ .Values.relp.port }}
      protocol: TCP
      name: {{ .Values.relp.name }}
    - port: {{ .Values.liveness_port.port }}
      targetPort: {{ .Values.liveness_port.port }}
      protocol: TCP
      name: {{ .Values.liveness_port.name }}
  selector:
    app: {{ template "logiq-flash.name" . }}
    release: {{ .Release.Name }}
