apiVersion: v1
appVersion: 1.4.2
description: A Helm chart for HAProxy Kubernetes Ingress Controller
home: https://github.com/haproxytech/helm-charts/tree/master/kubernetes-ingress
icon: http://www.haproxy.org/img/HAProxyCommunityEdition_60px.png
keywords:
- ingress
- haproxy
kubeVersion: '>=1.12.0-0'
maintainers:
- email: mmhedhbi@haproxy.com
  name: Moemen Mhedhbi
- email: bassmann@haproxy.com
  name: Baptiste Assmann
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: kubernetes-ingress
sources:
- https://github.com/haproxytech/kubernetes-ingress
version: 1.1.1
