{{- if .Values.ingress.enabled -}}
{{- $fullName := include "logiq.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    {{- include "logiq.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: logiq-ingress-{{ .Release.Namespace }}
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: "/"
spec:
  tls:
    - hosts:
        - {{ required "A valid domain is required. Use --set global.domain=<domain_name>" .Values.global.domain | quote }}
      {{ if .Values.ingress.tlsSecretName }}
      secretName:  {{ .Values.ingress.tlsSecretName }}
      {{ end }}
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
        - path: /
          backend:
            serviceName: coffee
            servicePort: 80
        - path: /v1
          backend:
            serviceName: logiq-flash
            servicePort: 9999
{{- end }}
