apiVersion: v1
kind: Service
metadata:
  name: beetle-coordinator
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.beetle_coordinator.targetPort | quote}}
    port: {{ .Values.beetle_coordinator.containerPort }}
    targetPort: {{ .Values.beetle_coordinator.targetPort }}
  selector:
    app: beetle-coordinator
