---
apiVersion: v1
kind: Service
metadata:
  name: beetle-worker
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.beetle_worker.targetPort | quote }}
    port: {{ .Values.beetle_worker.containerPort }}
    targetPort: {{ .Values.beetle_worker.targetPort }}
  selector:
    app: beetle-worker
